//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialSiteV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string User { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
        public string FavoriteTitle1 { get; set; }
        public string FavoriteContent1 { get; set; }
        public string FavoriteTitle2 { get; set; }
        public string FavoriteContent2 { get; set; }
        public string FavoriteTitle3 { get; set; }
        public string FavoriteContent3 { get; set; }
        public string ImageLink { get; set; }
    }
}
